apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gazette.fullname" . }}
  labels:
    app: {{ template "gazette.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
  {{ toYaml .Values.strategy | indent 2 }}
  template:
    metadata:
      labels:
        app: {{ template "gazette.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: scratch
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ template "gazette.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: service
        - containerPort: {{ .Values.service.monitoringPort }}
          name: monitoring
        args: [
          "/go/bin/gazette2",
          "-config", "/etc/config/config.yaml",
        ]
        env:
        - name: RW_DIRECTORIES
          value: /var/tmp
        {{ if .Values.aws }}
        - name: AWS_ENDPOINT
          value: {{ .Values.aws.endpoint }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.aws.accessKeyID }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.aws.secretKey }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.aws.defaultRegion }}
        {{ end }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPEC_ID_SUFFIX
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPEC_ENDPOINT
          value: "http://$(POD_IP):{{ .Values.service.port }}"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /var/tmp
          name: scratch
        - mountPath: /etc/config
          name: config-volume
{{- if .Values.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "gazette.name" . }}
            topologyKey: kubernetes.io/hostname
{{- end}}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
